name: 001caicai

on:
  schedule:
  - cron: '02 13,15,17,19,21,23,1,3,5,7 * * *'  #5-7-9-11-13-15-17-19-21-23 》02分&&&
  workflow_dispatch:
    分支:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install numpy          
        run: pip install 'numpy==1.26.4'
      - name: Install dependencies
        run: pip install selenium requests futures eventlet
      - name: Install dependencies
        run: pip install opencv-python requests 
      - name: Install dependencies
        run: pip install Beautifulsoup4 requests 
      - name: Install dependencies
        run: pip install translate requests 
        
      - name: Run iptv
        run: python ${{ github.workspace }}/ZUZU-PY/#CAIJI.py
         
      - name: Commit results
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automatic update"
            git push
            else
              echo "No changes detected, skipping commit."
            fi
